image: Visual Studio 2019

before_build:
- nuget restore "Homework.C-sharp/Task 1.1/Task 1.1.sln"

build:
 project: "Homework.C-sharp/Task 1.1/Task 1.1.sln"

test_script:
- dotnet test "Homework.C-sharp/Task 1.1/Task 1.1.sln"