image: Visual Studio 2019

before_build:
- nuget restore Homework.C-sharp/blob/Task-1.1/Task%201.1/Task%201.1.sln

build:
 project: Homework.C-sharp/blob/Task-1.1/Task%201.1/Task%201.1.sln

test_script:
- dotnet test Homework.C-sharp/blob/Task-1.1/Task%201.1/Task%201.1.sln